CREATE TABLE country (
id INTEGER  NOT NULL AUTO_INCREMENT,
name VARCHAR(128) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE VEHICLE_EXTERNAL_INFORMATION (
ID INTEGER  NOT NULL AUTO_INCREMENT,
LICENSE VARCHAR(10) NOT NULL,
COUNTRY_CODE VARCHAR(02) NOT NULL,
RISK_FACTOR DECIMAL(3,2) NOT NULL,
NUMBER_DOORS INTEGER,
FUEL_TYPE VARCHAR(20) NOT NULL,
POWER INTEGER NOT NULL,
PRIMARY KEY (ID));
